name: Build

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build_dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Docker login
        run: gcloud auth configure-docker
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Build & push Docker images
        env:
          REF: ${{ github.ref }}
          REGISTRY: gcr.io/${{ secrets.GCP_PROJECT_ID }}
        run: |
          cd docker
          chmod +x build.sh
          if [ $REF == 'refs/heads/master' ]
          then
            ./build.sh -s -p
          else
            ./build.sh -p
          fi
      - name: Cleanup registry
        run: |
          export IMAGES="$(gcloud container images list-tags gcr.io/${{ secrets.GCP_PROJECT_ID }}/auth/directory/api --filter='-tags:*' --format='get(digest)' --limit=unlimited | awk '{print "gcr.io/${{ secrets.GCP_PROJECT_ID }}/auth/directory/api@" $1}' | xargs)"
          echo "Deleting images: $IMAGES"
          gcloud container images delete --quiet $IMAGES
